name: Deploy

on:
    push:
        branches: [release]

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        environment: NPM
        steps:
            - uses: actions/checkout@v4
              id: checkout-repo
              name: Checkout Repository

            - uses: actions/setup-node@v3
              name: Setup node
              with:
                  node-version: '20.x'
                  registry-url: 'https://registry.npmjs.org'

            - run: yarn
              name: Install dependencies

            - run: npm publish --access public --verbose
              name: Deploy
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
