name: Build and run tests

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[ci skip]')"

        steps:
            - uses: actions/checkout@v4
              id: checkout-repo
              name: Checkout Repository

            - uses: actions/setup-node@v3
              name: Setup node
              with:
                  node-version: '20.x'

            - run: yarn
              name: Install dependencies

            - run: yarn build
              name: Build code

            - run: yarn test
              name: Run tests

            - run: yarn docs
              name: Build docs
